# Author: Nihil Project
# Beak through their web apps.

FROM archlinux:latest

ARG TAG="local"
ARG VERSION="local"
ARG BUILD_DATE="n/a"

LABEL org.nihil.tag="${TAG}"
LABEL org.nihil.version="${VERSION}"
LABEL org.nihil.build_date="${BUILD_DATE}"
LABEL org.nihil.app="Nihil"
LABEL org.nihil.variant="web"

COPY build /opt/nihil/build/
COPY runtime /opt/nihil/runtime/
RUN chmod +x /opt/nihil/runtime/entrypoint.sh /opt/nihil/runtime/load_my_resources.sh /opt/nihil/runtime/browser_ui.sh

WORKDIR /opt/nihil/build
SHELL ["/bin/bash", "-c"]

RUN chmod +x entrypoint.sh && \
    ./entrypoint.sh package_base && \
    ./entrypoint.sh install_core_tools && \
    ./entrypoint.sh install_mod_web && \
    ./entrypoint.sh install_mod_network && \
    ./entrypoint.sh install_mod_credential && \
    ./entrypoint.sh install_mod_misc && \
    ./entrypoint.sh healthcheck core_tools mod_web mod_network mod_credential mod_misc resources

WORKDIR /workspace
SHELL ["/usr/bin/zsh", "-c"]
ENTRYPOINT ["/opt/nihil/runtime/entrypoint.sh"]
